-- Simulation Tables
-- These tables perfectly mirror the live environment to ensure isolated testing.

-- 1. Simulation Scenarios (Stores uploaded JSON scenarios)
CREATE TABLE IF NOT EXISTS simulation_scenarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    data JSONB NOT NULL,
    is_active BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure only one active scenario per user
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_scenario_per_user 
ON simulation_scenarios (user_id) 
WHERE is_active = true;

-- 2. Simulation User Locations
CREATE TABLE IF NOT EXISTS simulation_user_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    state BIGINT REFERENCES states(code),
    district BIGINT REFERENCES districts(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Simulation Notifications
CREATE TABLE IF NOT EXISTS simulation_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    weather_alert_id TEXT,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    delivery_method TEXT NOT NULL CHECK (delivery_method IN ('in_app', 'sms', 'email')),
    status TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed')),
    sent_at TIMESTAMP WITH TIME ZONE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Setup RLS
ALTER TABLE simulation_scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulation_user_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulation_notifications ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can manage their own scenarios"
    ON simulation_scenarios FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can manage their own simulation locations"
    ON simulation_user_locations FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own simulation notifications"
    ON simulation_notifications FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "System can insert simulation notifications"
    ON simulation_notifications FOR INSERT WITH CHECK (auth.uid() = user_id);
