import type { Metadata } from "next";
import Link from "next/link";
import AlertTicker from './components/AlertTicker';
import LogoutButton from './components/LogoutButton';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*
          Global top navigation bar
          - placed inside RootLayout so every page renders it automatically
          - use comments and section markers for easy extension
        */}
        <header className="fixed top-0 inset-x-0 z-50 w-full bg-transparent text-zinc-50 shadow-md">
          {/* max-w-7xl mx-auto    --- add to nav classname if u want*/}
          <nav className=" px-4 sm:px-6 lg:px-8">
            <div className="flex h-16 items-center justify-between">
              {/* Logo / branding section */}
              <div className="flex-shrink-0">
                <Link href="/" className="text-xl font-bold">
                  Emergency OS
                </Link>
              </div>

              {/* Main navigation links */}
              <div className="hidden md:flex space-x-4">
                {/* Home button */}
                <Link
                  href="/"
                  className="px-3 py-2 rounded-md text-sm font-medium hover:bg-zinc-700"
                >
                  Home
                </Link>

                {/* Map page button */}
                <Link
                  href="/world-map"
                  className="px-3 py-2 rounded-md text-sm font-medium hover:bg-zinc-700"
                >
                  World Map
                </Link>

                {/* Register / login button */}
                {/* <Link
                  href="/Register"
                  className="px-3 py-2 rounded-md text-sm font-medium hover:bg-zinc-700"
                >
                  Register
                </Link> */}

                {/*
                  Additional links can be added below:
                  <a href="/other" className="...">Other</a>
                */}
              </div>

              {/* Utility section - user actions (logout, profile, settings) */}
              <div className="flex items-center gap-4">
                {/* Render LogoutButton in inline mode so it sits inside the navbar */}
                <LogoutButton inline />
              </div>
            </div>
          </nav>
        </header>

        {children}

        {/* Global alert/news ticker overlay - rendered outside page flow */}
        <AlertTicker />
      </body>
    </html>
  );
}
